# Generated by Django 3.0.6 on 2020-05-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0004_uploadedimage_title_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='description',
        ),
    ]
